NRPT-432: remove isPublished flags from flavour records
bcgov/NRPTI pull request #625
Opened 2020-09-24 18:35 UTC by mtCarto

* [NRPT-432](https://bcmines.atlassian.net/browse/NRPT-432)

2020-09-25 15:25 UTC, KitArmstrong commented on angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts
> +            this.router.navigate(['mines', this.collection.project, 'collections', this.collection._id, 'detail']);
Nice catch!

2020-09-25 15:30 UTC, KitArmstrong requested changes
With a quick search it looks like 'isBcmiPublished' is being checked in at least one component's HTML. As per the last AC on this ticket it that flag should only ever be checked for filtering. HTML should always look at the read array.

2020-09-25 17:49 UTC, mtCarto commented
Cleaned up other references to isBcmiPublished flag in table-row components. Should be all of them now

2020-09-25 17:54 UTC, KitArmstrong approved these changes

2020-09-28 18:26 UTC, MaxWardle approved these changes

2020-09-28 19:34 UTC, merged