NRPT-429 and NRPT-454: BCMI collection revisions
bcgov/NRPTI pull request #633
Opened 2020-10-01 18:25 UTC by danieltruong

Collection uses flavour id instead of master. Removing collectionId from master records

2020-10-01 21:19 UTC, KitArmstrong requested changes
Appears to be an issue with created records.  After I associate a new record to a collection it no longer appears in the Mine Record List.  Even if I remove it from the collection it does not return.

Steps to reproduce:
- Go to a Mine's Record List page
- Create a new record 
- Select the new record and choose "Add to Existing Collection"
- Update the collection
- Return to the Mine's Record List page and search for the record that was created

This same issue occurs if the mine is created from inside a collection too.

2020-10-01 21:29 UTC, danieltruong commented
> Appears to be an issue with created records. After I associate a new record to a collection it no longer appears in the Mine Record List. Even if I remove it from the collection it does not return.
> 
> Steps to reproduce:
> 
> * Go to a Mine's Record List page
> * Create a new record
> * Select the new record and choose "Add to Existing Collection"
> * Update the collection
> * Return to the Mine's Record List page and search for the record that was created
> 
> This same issue occurs if the mine is created from inside a collection too.

I can't seem to recreate this.

2020-10-01 22:36 UTC, danieltruong commented
> Appears to be an issue with created records. After I associate a new record to a collection it no longer appears in the Mine Record List. Even if I remove it from the collection it does not return.
> 
> Steps to reproduce:
> 
> * Go to a Mine's Record List page
> * Create a new record
> * Select the new record and choose "Add to Existing Collection"
> * Update the collection
> * Return to the Mine's Record List page and search for the record that was created
> 
> This same issue occurs if the mine is created from inside a collection too.

48cfb676f269f621135169c8388ec0fc55ee04b7

2020-10-02 15:03 UTC, marklise approved these changes

2020-10-02 15:53 UTC, KitArmstrong approved these changes

2020-10-02 16:35 UTC, merged