NRPT-556: update search controller to redact issuedTo based on role
bcgov/NRPTI pull request #710
Opened 2020-12-08 23:30 UTC by mtCarto

- [NRPT-556](https://bcmines.atlassian.net/browse/NRPT-556)

2020-12-09 02:42 UTC, marklise commented on api/src/controllers/search.js
> +let AppRoles = constants.ApplicationRoles;
Unless modifying, technically should be `const`

2020-12-09 19:00 UTC, BcGovNeal approved these changes

2020-12-09 19:30 UTC, BcGovNeal requested changes
I test this again and it seems the `issuedTo` names are showing on the Record list when `issuedTo.read` doesn't have `admin:wf` but `read` does.  Record detail is redacting correctly though.

2020-12-09 19:41 UTC, mtCarto commented
I'll take a look and correct this

2020-12-10 19:32 UTC, mtCarto commented
Should be working as expected now, requires the extra migration to prevent redaction of company names.

2020-12-10 21:38 UTC, BcGovNeal approved these changes
IssuedTo is displaying as expected

2020-12-15 00:39 UTC, MaxWardle approved these changes
Very nice 👏

2020-12-15 17:04 UTC, merged