increase max file upload size to 400mb
bcgov/NRPTI pull request #782
Opened 2021-02-19 21:46 UTC by mtCarto

[NRPT-692](https://bcmines.atlassian.net/browse/NRPT-692)

Increase doc upload limit to 400mb

Can create a ~350mb and 500mb file with
`dd if=/dev/zero of=./foo.pdf bs=3m count=128`
`dd if=/dev/zero of=./fooBig.pdf bs=4m count=128`

2021-02-19 22:03 UTC, BcGovNeal commented
These 2 lines in the API seem like they could affect the upload size as well.  Although I didn't find them affecting anything locally.

https://github.com/mtCarto/NRPTI/blob/b709032e8436c9724164cb093b15faac2e41170c/api/app.js#L25-L26

2021-02-19 22:08 UTC, mtCarto commented
Good catch, I didn't notice anything locally either with the current settings. Increased it to match the new limit to make it consistent at least.

2021-02-19 22:11 UTC, BcGovNeal approved these changes

2021-02-22 07:55 UTC, marklise requested changes

2021-02-22 07:55 UTC, marklise commented on api/app.js
> +app.use(bodyParser.urlencoded({ limit: '400mb', extended: true }));
These entries are not quite the right spot to adjust file upload limits as they only restrict the size of the json or urlencoded based payloads.  FormData file uploads are handled separately from the bodyParser module.  This is why you're not seeing an effect when adjusting these values.    There are technically two spots to limit, 1) in the front end, which your earlier change covers, and 2) in the API where we actually receive the data.  We could use something like npm package `multer` in the api.  Mind you the `multer-s3` package might a be better option given what we are doing but I don't think it supports limiting filesizes.

2021-02-22 18:57 UTC, marklise approved these changes

2021-02-22 22:34 UTC, merged