NRPT-654: implement ENV-EPD role controls in api and nrpti frontend
bcgov/NRPTI pull request #787
Opened 2021-02-24 20:58 UTC by mtCarto

Role controls for ENV-EPD role, includes necessary api and front-end updates.
- API: [NRPT-654](https://bcmines.atlassian.net/browse/NRPT-654)
- UI: [NRPT-353](https://bcmines.atlassian.net/browse/NRPT-353)

2021-02-25 16:45 UTC, marklise commented on api/src/controllers/document-controller.js
> +  sslEnabled: false,
Keep ssl enabled.

2021-02-25 16:46 UTC, marklise commented on api/src/controllers/post/permit.js
> +
Indentation

2021-02-25 17:05 UTC, mtCarto commented on api/src/controllers/document-controller.js
> +  sslEnabled: false,
Removing, only for local testing.

2021-02-25 17:57 UTC, marklise approved these changes

2021-02-25 21:32 UTC, BcGovNeal requested changes
Permit flavour records are missing the ENV-EPD role and cause an error when editing Permit records

2021-02-26 19:46 UTC, danieltruong approved these changes

2021-02-26 20:02 UTC, merged