NRPT-546: added record search by keyword in outcome description field in nrpti-admin, nrced
bcgov/NRPTI pull request #806
Opened 2021-03-16 19:09 UTC by cameronpettit

2021-03-17 18:05 UTC, mtCarto approved these changes
Looks good, the migrations work, outcome description is being hit by the keyword search now.

2021-03-17 18:05 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
> +      // console.log(this.queryParams, this.queryParams['subset'], searchPackage);
Remove this unused log

2021-03-17 18:27 UTC, cameronpettit commented on angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
> +      // console.log(this.queryParams, this.queryParams['subset'], searchPackage);
log removed

2021-03-18 16:10 UTC, BcGovNeal requested changes
A few minor things to fix please.

2021-03-18 16:10 UTC, BcGovNeal commented on api/openshift/cron.yaml
> +                        -d '{"taskType":"updateMaterializedView", "materializedViewSubset":"outcomeDescription"}' \
Should be `outcomeDescriptionSubset` instead of `outcomeDescription` here

2021-03-18 16:10 UTC, BcGovNeal commented on api/materialized_views/search/outcomeDescriptionSubset.js
> +    db.close();
Don't close the DB here, it causes the API to crash after running this script.   Just remove this line :)

2021-03-18 16:10 UTC, BcGovNeal commented on api/materialized_views/search/outcomeDescriptionSubset.js
> +    db.close();
Don't close the DB here, it causes the API to crash after running this script

2021-03-18 20:13 UTC, BcGovNeal approved these changes
Looks good!

2021-03-18 20:13 UTC, BcGovNeal commented on api/migrations/20210315213010-createOutcomeDescriptionSubset.js
>  let outcomeDescriptionUpdate = require('../materialized_views/search/outcomeDescriptionSubset');
Could remove this import now

2021-03-18 21:51 UTC, merged