NRPT-407: migration to add issuing agency and role to historical NRCED records
bcgov/NRPTI pull request #811
Opened 2021-03-22 15:46 UTC by cameronpettit

2021-03-23 21:40 UTC, BcGovNeal requested changes

2021-03-23 21:40 UTC, BcGovNeal commented on api/migrations/20210316214525-addIssuingAgencyAndRoleToHistoricalNRCED.js
> +    await ocersRecords.forEach(async record => {
The `await` here isn't actually waiting for the DB updates to finish.  One way around this is to convert the `forEach` to a `for...of` loop and await on the DB update code.

The `db.update` calls in `updateRecord` should have await, and `updateRecord` should be async.  Then each of the `updateRecord` calls should also have await.

I'd also use `updateOne` or `updateMany`.  `update` seems to be a deprecated function.

2021-03-24 15:15 UTC, BcGovNeal commented on api/migrations/20210316214525-addIssuingAgencyAndRoleToHistoricalNRCED.js
> +        db.update(
Missed one :P

2021-03-24 15:20 UTC, cameronpettit commented on api/migrations/20210316214525-addIssuingAgencyAndRoleToHistoricalNRCED.js
> +        db.update(
oops.. I will get that

2021-03-24 16:13 UTC, BcGovNeal approved these changes
Looks good, just couple minor (and obscure) issues left.

2021-03-24 16:13 UTC, BcGovNeal commented on api/src/utils/constants/misc.js
> +  AGENCY_ENV_COS: 'Conservation Officer Service',
Use `Conservation Officer Service (COS)` to match other records in DB

2021-03-24 16:13 UTC, BcGovNeal commented on api/src/utils/constants/misc.js
> +  AGENCY_BCMI: 'Ministry of Energy, Mines and Low Carbon Initiatives',
Use `EMLI` to match other records in DB

2021-03-24 22:14 UTC, mtCarto reviewed
MIgration looks good, address the string changes suggested by Neal and this is good to go

2021-03-25 20:37 UTC, mtCarto approved these changes

2021-03-26 15:52 UTC, merged