NRPT-758: updated front ends to accept arrays
bcgov/NRPTI pull request #883
Opened 2021-07-15 23:12 UTC by MaxWardle

[https://bcmines.atlassian.net/browse/NRPT-758](https://bcmines.atlassian.net/browse/NRPT-758)

Api changes in [NRPT-757](https://github.com/bcgov/NRPTI/pull/846)

2021-07-21 18:55 UTC, mtCarto approved these changes
Code looks great, comments are just some tidying and cleanup.

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html
> +          <!-- <div class="grid-item__row">
remove commented code

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-detail/certificate-amendments-detail.component.html
> +          <!-- <div class="grid-item__row">
remove

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
> +// import { Legislation } from '../../../../../../common/src/app/models/master/common-models/legislation';
remove

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update memberof

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update memberOf

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
> +   * @memberof CourtConvictionAddEditComponent
nit: update name

2021-07-21 18:55 UTC, mtCarto commented on angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
nit: update name

2021-07-21 20:43 UTC, BcGovNeal requested changes
There is a bug with Add Legislation button.  

When editing records where `sourceSystemRef !== 'nrpti'`, the form controls are disabled.  Then when you go add a new legislation, the FormArray deletes FormGroups that are disabled.   This causes the original legislation to be removed when you add a new legislation.

The disabled values are still available through `getRawValue()` instead of `value`.  But I think in this case we should just disable the Add button if the legislations are not supposed to be edited.

2021-07-22 16:16 UTC, MaxWardle commented
> There is a bug with Add Legislation button.
> 
> When editing records where `sourceSystemRef !== 'nrpti'`, the form controls are disabled. Then when you go add a new legislation, the FormArray deletes FormGroups that are disabled. This causes the original legislation to be removed when you add a new legislation.
> 
> The disabled values are still available through `getRawValue()` instead of `value`. But I think in this case we should just disable the Add button if the legislations are not supposed to be edited.

Good catch, thanks!

2021-07-22 16:16 UTC, MaxWardle commented on angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
> +   * @memberof AdministrativePenaltyAddEditComponent
Missed these, thank you!

2021-07-22 18:25 UTC, BcGovNeal approved these changes

2021-07-22 22:15 UTC, merged