NRPT-788 and NRPT-809
bcgov/NRPTI pull request #906
Opened 2021-08-19 22:47 UTC by cameronpettit

NRPT-809 populate description field in collapsed row

NRPT-788 changes to card layouts, warnings added

NRPT-809 moving outcome description field

NRPT-788 and NRPT-809

2021-08-20 16:28 UTC, BcGovNeal requested changes
Got some mislabeled fields

2021-08-20 16:28 UTC, BcGovNeal commented on angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html
> +            <label class="grid-item-name">Date Issued</label>
Should be Issued To here

2021-08-20 16:28 UTC, BcGovNeal commented on angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html
> +            <label class="grid-item-name">Date Issued</label>
Should be Issued To

2021-08-20 16:28 UTC, BcGovNeal commented on angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html
> +            <label class="grid-item-name">Date Issued</label>
Should be Issued To

2021-08-20 19:24 UTC, BcGovNeal approved these changes

2021-08-24 16:33 UTC, marklise approved these changes

2021-08-24 16:33 UTC, merged